// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositorio.FonteDeDados;

namespace Repositorio.Migrations
{
    [DbContext(typeof(PersisteContext))]
    [Migration("20220427063456_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("AspNetCore_Webhook")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:IdentityIncrement", 1)
                .HasAnnotation("SqlServer:IdentitySeed", 1)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dominio.Webhook_mensagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Atualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("atualizacao");

                    b.Property<DateTime>("Criacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("criacao");

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("descricao");

                    b.Property<long?>("PerfilId")
                        .HasColumnType("bigint");

                    b.Property<int>("Perfil_Id")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("idMensagem");

                    b.HasIndex("PerfilId");

                    b.ToTable("tbWebhook_mensagem");
                });

            modelBuilder.Entity("Dominio.Webhook_perfil", b =>
                {
                    b.Property<long?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Atualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("atualizacao");

                    b.Property<string>("Chave")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("chave");

                    b.Property<DateTime>("Criacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("criacao");

                    b.Property<string>("Nome")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("idPerfil");

                    b.ToTable("tbWebhook_perfil");
                });

            modelBuilder.Entity("Dominio.Webhook_mensagem", b =>
                {
                    b.HasOne("Dominio.Webhook_perfil", "Perfil")
                        .WithMany("Mensagens")
                        .HasForeignKey("PerfilId");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("Dominio.Webhook_perfil", b =>
                {
                    b.Navigation("Mensagens");
                });
#pragma warning restore 612, 618
        }
    }
}
